services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: telemetry_test
    networks:
      - observability
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U testuser -d telemetry_test']
      interval: 5s
      timeout: 5s
      retries: 5

  app-server:
    build: .
    container_name: app-server
    env_file: .env
    ports:
      - 3001:3001
    networks:
      - observability
    depends_on:
      postgres:
        condition: service_healthy

  beyla:
    image: grafana/beyla
    container_name: beyla
    privileged: true
    pid: 'service:app-server'
    environment:
      BEYLA_OPEN_PORT: 3001
      BEYLA_PROMETHEUS_PORT: 9464
      BEYLA_PROMETHEUS_FEATURES: application,application_process
    networks:
      - observability

networks:
  observability:
    external: true
