apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Grafana Pyroscope
    type: grafana-pyroscope-datasource
    url: http://pyroscope:4040

  - name: Tempo
    type: tempo
    url: http://tempo:3200
