{
 "title": "Vispyr Observability",
 "description": "Default observability dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   { "name": "DS_PYROSCOPE", "label": "Pyroscope", "query": "grafana-pyroscope-datasource" },
   { "name": "DS_TEMPO", "label": "Tempo", "query": "tempo" },
   { "name": "app", "label": "Application", "query": { "query": "label_values(service_name)" } },
   { "name": "route", "label": "Route", "query": { "query": "label_values(http_route)" } },
   { "name": "traceId", "label": "Trace ID" }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Average CPU Utilization Across All Logical Cores"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "System Memory Not Immediately Available Without Impact On Performance"
    }
   ]
  },
  {
   "title": "P99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, histogram_quantile(0.99, sum(rate(traces_spanmetrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", http_target=~\"$route\"}[5m])) by (le, span_name)))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Profiles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Profile",
   "type": "flamegraph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "labelSelector": "{}",
     "profileTypeId": "wall:wall:nanoseconds:wall:nanoseconds"
    }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Trace Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "limit": 20, "metricsQueryType": "range", "query": "{} | count() > 1", "tableType": "traces" }
   ]
  },
  {
   "title": "Trace Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    { "limit": 200, "metricsQueryType": "range", "query": "{} | count() > 1", "tableType": "traces" }
   ]
  },
  {
   "title": "Trace Waterfall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Trace Details",
     "type": "traces",
     "gridPos": { "h": 24, "w": 24, "x": 0, "y": 31 },
     "targets": [
      { "limit": 20, "metricsQueryType": "range", "query": "${traceId}", "tableType": "traces" }
     ]
    }
   ]
  }
 ]
}